# pre-commit file
# .pre-commit-config.yaml
# https://prek.j178.dev/

# To install, run:
# prek autoupdate && prek install

## To run for all files:
# prek run --all-files

repos:
- repo: https://github.com/betterleaks/betterleaks
  rev: v1.1.1
  hooks:
  - id: betterleaks

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-added-large-files
    args: [ "--maxkb=500" ]
  - id: check-yaml
  - id: check-toml
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: trailing-whitespace
