# pre-commit file
# .pre-commit-config.yaml
# https://pre-commit.com/

# To install, run:
# pre-commit autoupdate && pre-commit install

## To run for all files:
# pre-commit run --all-files

repos:
    - repo: https://github.com/gitleaks/gitleaks
      rev: v8.28.0
      hooks:
          - id: gitleaks

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v6.0.0
      hooks:
          - id: check-added-large-files
            args: ["--maxkb=500"]
          - id: check-yaml
          - id: check-toml
          - id: end-of-file-fixer
          - id: mixed-line-ending
          - id: trailing-whitespace
